src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"article" = "Article", "miniConsole" = "MiniConsole"})
 */

class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Unique
     */
    protected $title;

    /**
     * @ORM\Column(type="text")
     */
    protected $content;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $LastModifiedAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $image;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="relatedTo", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getLastModifiedAt(): ?\DateTimeInterface
    {
        return $this->LastModifiedAt;
    }

    public function setLastModifiedAt(\DateTimeInterface $LastModifiedAt): self
    {
        $this->LastModifiedAt = $LastModifiedAt;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setRelatedTo($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getRelatedTo() === $this) {
                $comment->setRelatedTo(null);
            }
        }

        return $this;
    }

}

src/Entity/MiniConsole.php
<?php

namespace App\Entity;

use App\Repository\MiniConsoleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MiniConsoleRepository::class)
 */
class MiniConsole extends Article
{

    /**
     * @ORM\Column(type="string")
     */
    private $ReleaseYear;

    /**
     * @ORM\Column(type="string")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $opinion;


    /**
     * @ORM\OneToMany(targetEntity=Games::class, mappedBy="emulatedOn")
     * @ORM\OrderBy({"name" = "ASC"})
     */
    private $games;


    public function __construct()
    {
        $this->games = new ArrayCollection();
    }



    public function getReleaseYear(): ?string
    {
        return $this->ReleaseYear;
    }

    public function setReleaseYear(string $ReleaseYear): self
    {
        $this->ReleaseYear = $ReleaseYear;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getOpinion(): ?string
    {
        return $this->opinion;
    }

    public function setOpinion(string $opinion): self
    {
        $this->opinion = $opinion;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getLastModifiedAt(): ?\DateTimeInterface
    {
        return $this->LastModifiedAt;
    }

    public function setLastModifiedAt(\DateTimeInterface $LastModifiedAt): self
    {
        $this->LastModifiedAt = $LastModifiedAt;

        return $this;
    }

    /**
     * @return Collection|Games[]
     */
    public function getGames(): Collection
    {
        return $this->games;
    }

    public function addGame(Games $game): self
    {
        if (!$this->games->contains($game)) {
            $this->games[] = $game;
            $game->setEmulatedOn($this);
        }

        return $this;
    }

    public function removeGame(Games $game): self
    {
        if ($this->games->contains($game)) {
            $this->games->removeElement($game);
            // set the owning side to null (unless already changed)
            if ($game->getEmulatedOn() === $this) {
                $game->setEmulatedOn(null);
            }
        }

        return $this;
    }

}

src/Controller/RetroboxController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Doctrine\ORM\EntityManagerInterface;

use App\Entity\MiniConsole;
use App\Entity\Article;
use App\Entity\Comment;
use App\Form\CommentType;
use App\Repository\ArticleRepository;
use App\Repository\MiniConsoleRepository;
use App\Repository\CommentRepository;

class RetroboxController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index()
    {
        return $this->render('retrobox/index.html.twig');
    }

    /**
     * @Route("/mentions-legales", name="legal")
     */
    public function legal()
    {
        return $this->render('legalNotice.html.twig');
    }

    /**
     * @Route("/mini-consoles", name= "mini-consoles")
     */
    public function displayMachines( MiniConsoleRepository $miniConsolesRepo)
    {
    
        $miniConsoles = $miniConsolesRepo->findBy( array(), array('title' => 'asc'));

        return $this->render('retrobox/consoles.html.twig', [
            'miniConsoles' => $miniConsoles
        ]);
    }

    /**
     * @Route("/mini-consoles/{title}", name= "one-mini")
     */

    public function displayAMachine($title, MiniConsole $miniConsole, Request $request, EntityManagerInterface $manager, CommentRepository $commentrepo)
    {

        $comments = $miniConsole->getComments();

        $comment = new Comment();
        $formComment = $this->createForm(CommentType::class, $comment);
    
        $formComment->handleRequest($request);
        if ($formComment->isSubmitted() && $formComment->isValid())
        {
    
            $comment->setCreatedAt(new \DateTime());
            $comment->setisReported(false);
            $comment->setRelatedTo($miniConsole);
            $manager->persist($comment);
            $manager->flush();
    
            return $this->redirectToRoute('one-mini', ['title' => $title]);
    
        }

        if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['report']))
        {
            $reportedComment = $commentrepo->findOneById($_POST['report']);
            $reportedComment->setIsReported('true');
            $manager->persist($reportedComment);
            $manager->flush();

            return $this->render('retrobox/display-one.html.twig', [
                'miniConsole' => $miniConsole,
                'formComment' => $formComment->createView(),
                'message' => 'Le commentaire a bien été signalé.'
            ]);
        }
        
        return $this->render('retrobox/display-one.html.twig', [
            'miniConsole' => $miniConsole,
            'formComment' => $formComment->createView(),
            'message' => ''
        ]);
        

    }
    /**
     * @Route("/contact", name="contact")
     */
    public function contact(Request $request, $name = null, $email = null, $content = null , \Swift_Mailer $mailer)
    {
        $defaultData = ['message' => 'Entrez votre message...'];
        $form = $this->createFormBuilder($defaultData)
            ->add('nom', TextType::class)
            ->add('email', EmailType::class)
            ->add('message', TextareaType::class)
          
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $data = $form->getData();
            
            $name = $data ['nom'] ;
            $email = $data ['email'];
            $content = $data ['message'];

            $confirm = (new \Swift_Message('Feedback Email'))
                    ->setFrom('contact@r3trobox.fr')
                    ->setTo('contact@r3trobox.fr')
                    ->setBody(
                        $this->renderView(
                            // templates/contact.html.twig
                            'confirm.html.twig',[
                                'name' => $name,
                                'content' => $content,
                                'email' => $email]
                        ),
                        'text/html'
                    );

            $mailer->send($confirm);

            $message = (new \Swift_Message('Confirmation Email'))
                    ->setFrom('contact@r3trobox.fr')
                    ->setTo($email)
                    ->setBody(
                        $this->renderView(
                            // templates/contact.html.twig
                            'confirm.html.twig',[
                                'name' => $name,
                                'content' => $content,
                                'email' => $email]
                        ),
                        'text/html'
                    );

            $mailer->send($message);
            
            return $this->render(
                            'contact.html.twig',
                            ['formContact' => $form->createView(),
                            'message' => 'Merci ! Votre message a bien été envoyé ! Vous allez recevoir un mail de confirmation']
            );
            
        }
        return $this->render('contact.html.twig', [
            'formContact' => $form->createView(),
            'message' => 'Vous pouvez nous contacter à l\'aide de ce formulaire'
        ]);
        
    }


    /**
     * @Route("/Article/{title}", name= "article")
     */

    public function displayArticle($title, Request $request, Article $article, EntityManagerInterface $manager, CommentRepository $commentRepo)
    {

        $comments = $article->getComments();

        $comment = new Comment();
        $formComment = $this->createForm(CommentType::class, $comment);

        $formComment->handleRequest($request);
        if ($formComment->isSubmitted() && $formComment->isValid())
        {

            $comment->setCreatedAt(new \DateTime());
            $comment->setisReported(false);
            $comment->setRelatedTo($article);
            $manager->persist($comment);
            $manager->flush();

            return $this->redirectToRoute('article', ['title' => $title]);

        }
        if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['report']))
        {
            $reportedComment = $commentRepo->findOneById($_POST['report']);
            $reportedComment->setIsReported('true');
            $manager->persist($reportedComment);
            $manager->flush();

            return $this->render('retrobox/article.html.twig', [
                'article' => $article,
                'comments' => $comments,
                'formComment' => $formComment->createView(),
                'message' => 'Le commentaire a bien été signalé.'
            ]);
        }

        return $this->render('retrobox/article.html.twig', [
            'article' => $article,
            'comments' => $comments,
            'formComment' => $formComment->createView(),
            'message' => ''
        
        ]);
    }

}

    

templates/retrobox/article.html.twig
{% extends 'base.html.twig' %}

{% block title %}Retrobox - Do It Yourself {% endblock %}

{% block body %}
    <h2>{{ article.title }}</h2>
    <div class="row">
        <span class=" offset-6 col-4 ">Dernière Mise à jour de l'article : {{ article.lastModifiedAt | date('d/m/Y')}} à {{article.lastModifiedAt | date('H:i')}} </span>
    </div>
    <div class="row">
        <div class="row">
            <div id="intro-container" class="col-lg-6">
                <button id="intro-btn" class="btn-primary">Afficher l'intro</button>
                <p id="intro-text" class="col-lg-12">C’est bien gentil toutes ces mini-consoles, mais il doit bien exister un moyen de rejouer à ce qu’on veut sans acheter toutes les machines de la terre, non ? <br/>
Oui ! Il existe bien des solutions, dont une a largement l'avantage sur les autres : le Raspberry Pi.<br/>
Il s’agit, pour faire simple, d’un ordinateur miniature conçu par un professeur d'université dans un but pédagogique (plus simple à comprendre et à programmer qu'un PC). Pour l’utiliser de façon optimale, des passionnés ont conçu un système d’exploitation dédié au rétrogaming : Recalbox ! <br/>
A partir de cette alliance, on obtient la possibilité de jouer à la Super Nintendo, la Sega Master System, l’Amiga et tant d’autres… Et ça, branchée sur la télé du salon ou sur n’importe quel écran HDMI, connectée à notre manette Bluetooth préférée (ou USB), à l’aide d’une machine pas plus grande qu’un paquet de cigarettes (désolé pour l’analogie, mais vous avez l’image), et enfin qui ne consomme pas plus de courant que votre chargeur de smartphone !<br/></p>
            </div>
            <div class="col-lg-6">
                <img src="{{ asset(article.image) }}" alt="image">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                {{ article.content | raw }}
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12 col-md-12">
            <h3>Commentaires</h3>
        </div>
        <div class="col-lg-12 col-md-12">
            <h4>{{ message }}</h4>
        </div>
        <div class="row">

            {% for comment in article.comments %}
                {% if comment.isReported == false %}
                    <div class="card" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">{{comment.author}}</h5>
                            <p class="card-text">Écrit le {{comment.createdAt  | date('d/m/Y')}} à {{comment.createdAt | date('H:i')}}<br/>
                                {{ comment.content | raw }}
                            </p>
                            <form action="" method="post">
                                <button type="submit" name="report" value="{{comment.id}}" class="btn btn-warning btn-report">Signaler</button>
                            </form>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            {{ form_start(formComment) }}

                {{ form_row(formComment.author, { 'attr': {'placeholder':"Entrez votre nom"}} )}}
            
                {{ form_row(formComment.content , { 'attr': {'placeholder':"Entrez votre message"}} )}}

                <button type="submit" class="btn btn-primary">Soumettre</button>

            {{ form_end(formComment) }}
        </div>
    </div>
        
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/intro.js') }}"></script>
{% endblock %}

templates/retrobox/consoles.html.twig
{% extends 'base.html.twig' %}

{% block title %}Retrobox - Les Mini-Consoles{% endblock %}

{% block body %}
    <h1>Mini-Consoles</h1>
    <div class="row">
    
        {% for miniConsole in miniConsoles %}
            <div class="col-lg-4 col-md-6">

                <div class="card">
                    <img class="card-img-top" src={{ asset(miniConsole.image) }} alt="Card image cap"/>
                    <div class="card-body">
                        <h5 class="card-title">{{miniConsole.title}}</h5>
                        <p class="card-text"><span class="badge badge-primary">Année de sortie : {{miniConsole.ReleaseYear}}</span>  |  <span class="badge badge-info">Prix : {{miniConsole.price}}€</span> <br/>
                            Avis : {{miniConsole.opinion}}   |  Dernière MAJ de l'article : Le {{miniConsole.lastModifiedAt | date('d/m/Y')}} à {{miniConsole.lastModifiedAt | date('H:i')}}<br/>
                            {{ miniConsole.content[:20] | raw }}...
                            <a href="{{ path('one-mini', {'title': miniConsole.title }) }}" class="btn btn-primary">Lire la suite</a>
                        </p>
                    </div>
                </div>    

            </div>
        {% endfor %}
    
    </div>

    
    
{% endblock %}

templates/retrobox/display-one.html.twig
{% extends 'base.html.twig' %}

{% block title %}Retrobox - Les Mini-Consoles{% endblock %}


{% block body %}
    <h2>{{ miniConsole.title }}</h2>
    <div class="row">

        <span class="col-lg-3">Sortie : {{ miniConsole.releaseYear }} </span>
        <span class="col-lg-3">Prix : {{ miniConsole.price }} € </span>
        <span class="col-lg-3">Avis : {{ miniConsole.opinion }} </span>
        <span class="col-lg-3">Dernière MAJ de l'article : Le {{miniConsole.lastModifiedAt | date('d/m/Y')}} à {{miniConsole.lastModifiedAt | date('H:i')}}</span>

    </div>
    <div class="row">
        <div class="row">
            <div class="col-lg-6 col-sm-12">
                <p class="mc-content">{{ miniConsole.content | raw }}</p>
            </div>
            <div class="col-lg-6">
                <img src="{{ asset(miniConsole.image) }}" alt="image">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 col-sm-12">
            <div class="row">
                <div clas="col-lg-12">
                    <h3>Liste des Jeux</h3>
                </div>
                <div class="col-lg-12">
                    <table>
                        <thead>
                            <tr class="table-primary">
                                <th>Nom</th>
                                <th>Année</th>
                                <th>Genre</th>
                                {% if miniConsole.id == 12 %}
                                    <th>Plateforme d'origine</th>
                                {% endif %}
                            </tr>
                        </thead>
                        {% for game in miniConsole.games %}
                            <tr class="table-secondary">
                                <td>{{game.name}}</td>
                                <td>{{game.releaseYear}}</td>
                                <td>{{game.type}}</td>
                                {% if miniConsole.id == 12 %}
                                    <td>{{game.description}}</td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                            
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-sm-12">
            <div class="row">
                <div class="col-lg-12">
                    <h3>Commentaires</h3>

                    <h4>{{ message }}</h4>

                </div>
                <div class="col-lg-12">
                    {% for comment in miniConsole.comments %}

                        {% if comment.isReported == '0' %}
                            <div class="card" style="width: 18rem;">
                                <div class="card-body">
                                    <h5 class="card-title">{{comment.author}}</h5>
                                    <p class="card-text">Écrit le {{comment.createdAt  | date('d/m/Y')}} à {{comment.createdAt | date('H:i')}}<br/>
                                        {{ comment.content | raw }}
                                    </p>
                                    <form action="" method="post">
                                        <button type="submit" name="report" value="{{comment.id}}" class="btn btn-warning btn-report">Signaler</button>
                                    </form>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
 
                <div class="col-lg-12">
                    {{ form_start(formComment) }}

                        {{ form_row(formComment.author, { 'attr': {'placeholder':"Entrez votre nom"}} )}}
                            
                        {{ form_row(formComment.content , { 'attr': {'placeholder':"Entrez votre message"}} )}}

                        <button type="submit" class="btn btn-primary">Soumettre</button>

                    {{ form_end(formComment) }}
                </div>
            </div>
        </div>      
    </div>
        
{% endblock %}

templates/retrobox/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}R3trobox.fr{% endblock %}

{% block body %}

<div class="jumbotron">
    
    <h1 class="display-2">R3trobox</h1>
    
    
</div>
<div class="container">
    <div class="row">
        <h2>Bienvenue !</h2>
    </div>
    <div id="home-row" class="row">

    
        <p id="home-text" class="col-lg-12">
            Vous vous trouvez sur notre blog de retro-gaming francophone. 
            Nous sommes des amateurs de jeux vidéos depuis l'enfance et la nostalgie (dans l'air du temps) nous pousse à chercher les sensations de jeux de cette époque.<br/>
            Vous trouverez ici toutes sortes de moyens de rejouer "comme à l'époque" : <br/>
            <a href="{{ path('mini-consoles') }}"> Mini-consoles, Switch Online</a>,<br/>
            <a href="{{ path('article', {'title': 'DIY - Le Matériel' }) }}">Raspberry Pi 3B+,<br/>
            <a href="{{ path('article', {'title': 'DIY - Recalbox' }) }}">Recalbox</a>...<br/>
            Bref nous allons parler d'émulation.<br/>
            Dans la section "Mini-Consoles", vous trouverez un article pour chaque machine émulant une ancienne console ou un "ordinosaure".<br/>
            Ces articles sont là pour vous aider à faire le bon choix avant d'investir dans du matériel.<br/>
            Les articles "Matériel" et "Recalbox" vous permettront de vous lancer dans le DIY(fait-maison) en vous montrant la simplicité et les économies réalisées par certaines solutions.<br/>
            Pour toute question, n'hésitez pas à remplir un <a href="{{ path('contact') }}">Formulaire de Contact</a>.<br/>
            <br/>
            Bonne visite !<br/>
        </p>

    </div>
    
    

    


</div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}